/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardMyMarksRouteImport } from './routes/dashboard.my-marks'
import { Route as DashboardMyAttendanceRouteImport } from './routes/dashboard.my-attendance'
import { Route as DashboardMarksRouteImport } from './routes/dashboard.marks'
import { Route as DashboardFacultyRouteImport } from './routes/dashboard.faculty'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/dashboard/students',
  path: '/dashboard/students',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyMarksRoute = DashboardMyMarksRouteImport.update({
  id: '/dashboard/my-marks',
  path: '/dashboard/my-marks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyAttendanceRoute = DashboardMyAttendanceRouteImport.update({
  id: '/dashboard/my-attendance',
  path: '/dashboard/my-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMarksRoute = DashboardMarksRouteImport.update({
  id: '/dashboard/marks',
  path: '/dashboard/marks',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFacultyRoute = DashboardFacultyRouteImport.update({
  id: '/dashboard/faculty',
  path: '/dashboard/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/dashboard/courses',
  path: '/dashboard/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/dashboard/attendance',
  path: '/dashboard/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/faculty': typeof DashboardFacultyRoute
  '/dashboard/marks': typeof DashboardMarksRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-marks': typeof DashboardMyMarksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/faculty': typeof DashboardFacultyRoute
  '/dashboard/marks': typeof DashboardMarksRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-marks': typeof DashboardMyMarksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/faculty': typeof DashboardFacultyRoute
  '/dashboard/marks': typeof DashboardMarksRoute
  '/dashboard/my-attendance': typeof DashboardMyAttendanceRoute
  '/dashboard/my-marks': typeof DashboardMyMarksRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard/attendance'
    | '/dashboard/courses'
    | '/dashboard/faculty'
    | '/dashboard/marks'
    | '/dashboard/my-attendance'
    | '/dashboard/my-marks'
    | '/dashboard/profile'
    | '/dashboard/students'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/attendance'
    | '/dashboard/courses'
    | '/dashboard/faculty'
    | '/dashboard/marks'
    | '/dashboard/my-attendance'
    | '/dashboard/my-marks'
    | '/dashboard/profile'
    | '/dashboard/students'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard/attendance'
    | '/dashboard/courses'
    | '/dashboard/faculty'
    | '/dashboard/marks'
    | '/dashboard/my-attendance'
    | '/dashboard/my-marks'
    | '/dashboard/profile'
    | '/dashboard/students'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardFacultyRoute: typeof DashboardFacultyRoute
  DashboardMarksRoute: typeof DashboardMarksRoute
  DashboardMyAttendanceRoute: typeof DashboardMyAttendanceRoute
  DashboardMyMarksRoute: typeof DashboardMyMarksRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/dashboard/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-marks': {
      id: '/dashboard/my-marks'
      path: '/dashboard/my-marks'
      fullPath: '/dashboard/my-marks'
      preLoaderRoute: typeof DashboardMyMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-attendance': {
      id: '/dashboard/my-attendance'
      path: '/dashboard/my-attendance'
      fullPath: '/dashboard/my-attendance'
      preLoaderRoute: typeof DashboardMyAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/marks': {
      id: '/dashboard/marks'
      path: '/dashboard/marks'
      fullPath: '/dashboard/marks'
      preLoaderRoute: typeof DashboardMarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/faculty': {
      id: '/dashboard/faculty'
      path: '/dashboard/faculty'
      fullPath: '/dashboard/faculty'
      preLoaderRoute: typeof DashboardFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/dashboard/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/dashboard/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardFacultyRoute: DashboardFacultyRoute,
  DashboardMarksRoute: DashboardMarksRoute,
  DashboardMyAttendanceRoute: DashboardMyAttendanceRoute,
  DashboardMyMarksRoute: DashboardMyMarksRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
